services:

  app:
    build: ./app
    container_name: fastapi-app
    env_file:
      - .env
    depends_on:
      - db
      - minio
    networks:
      - nusantara-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - nusantara-network

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nusantara-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db
    networks:
      - nusantara-network
  
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - minio_data:/data
    networks:
      - nusantara-network

volumes:
  postgres_data:
  minio_data:
  
networks:
  nusantara-network:
    driver: bridge